### ISSUE TITLE
Repository name too generic

### ISSUE THREAD

**Issue by fredvd** [plone/helm-charts#2]
I'm  a bit concerned with calling this repository charts for helm charts.  Can we please rename it to plone.helmcharts ?  

There are many kind of charts. For example, Is this repo an official Plone add'on to add a Chart content type to Plone to store graphical charts?

**Comment by gforcada** [comment]
[_Naming is hard_](https://www.martinfowler.com/bliki/TwoHardThings.html) 😆

**Comment by ericof** [comment]
@fredvd, I do agree with @fabiorauber on this one. My personal feeling is that naming it plone-charts or plone.charts would be more confusing than the other way around.

**Comment by gforcada** [comment]
`helm-charts` or is that independent of `helm` itself (_me_ pretending I know what I'm writing about 👀 ).

If other technologies reuse that same word that might introduce confusion as well, but if it's unique for `helm` it should be fine ™️

**Comment by ericof** [comment]
@fabiorauber, what do you think about helm-charts?

**Comment by ericof** [comment]
Let's rename it to `helm-charts` and update documentation everywhere :-)
